# Generated by Django 5.2.3 on 2025-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatirimciHikaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('zorluk', models.TextField()),
                ('bugunku_durum', models.TextField()),
            ],
            options={
                'verbose_name': 'Yatırımcı Hikayesi',
                'verbose_name_plural': 'Yatırımcı Hikayeleri',
            },
        ),
    ]
