# Generated by Django 5.2.3 on 2025-06-26 08:46

from django.db import migrations

def load_stories(apps, schema_editor):
    YatirimciHikaye = apps.get_model('core', 'YatirimciHikaye')
    
    stories = [
        {
            'isim': 'Ray Dalio',
            'zorluk': '1982 yılında, Dalio tüm parasını yanlış bir ekonomik tahmin yüzünden kaybetti. Ekonominin çöküşünü beklerken piyasa yükseldi ve şirket çalışanlarını işten çıkarmak zorunda kaldı. O kadar parasız kaldı ki, ailesinden borç almak zorunda kaldı.',
            'bugunku_durum': 'Şu an dünyanın en büyük hedge fonlarından biri olan Bridgewater Associates\'in kurucusu. Kişisel serveti 20 milyar doları aşıyor.'
        },
        {
            'isim': 'Warren Buffett',
            'zorluk': '1970\'lerde yatırım yaptığı bazı şirketler iflas etti. Özellikle Berkshire Hathaway\'in ilk yıllarında tekstil işine tutunmaya çalışması milyonlarca dolar zarar ettirdi. Kendisi bile "en kötü yatırım kararımdı" dedi.',
            'bugunku_durum': 'Berkshire Hathaway CEO\'su ve dünyanın en saygı duyulan yatırımcısı. Yüz milyarlarca dolarlık bir şirketi yönetiyor.'
        },
        {
            'isim': 'Cathie Wood',
            'zorluk': '2021 sonrası teknoloji hisselerine yoğun yatırım yaptığı için büyük eleştiri aldı. ARK Invest hisseleri %70\'e varan değer kaybı yaşadı. Bazı yatırımcılar fonlarını geri çekti, medya tarafından ağır şekilde eleştirildi.',
            'bugunku_durum': 'Yenilikçi yatırım anlayışıyla hâlâ teknolojiye güveniyor. Birçok yatırımcı hâlâ ona uzun vadeli vizyoner olarak bakıyor.'
        },
        {
            'isim': 'Charlie Munger',
            'zorluk': 'Genç yaşta ilk evliliği boşanmayla sonuçlandı. Oğlu kanserden hayatını kaybetti. İlk yıllarda birçok yatırım kaybı yaşadı. Gözünü kaybetme riski yaşadı ama asla pes etmedi.',
            'bugunku_durum': 'Warren Buffett\'ın sağ kolu ve değer yatırımının en zeki isimlerinden biri olarak tarihe geçti.'
        },
        {
            'isim': 'Benjamin Graham',
            'zorluk': '1929 Büyük Buhranı\'nda servetinin büyük bir kısmını kaybetti. Borsa çöktüğünde öğrencilerine karşı utanma hissetti, çünkü birçok yatırım öğüdü işe yaramamıştı.',
            'bugunku_durum': '"Değer yatırımının babası" olarak bilinir. Warren Buffett\'ın ilham kaynağıdır.'
        },
        {
            'isim': 'Elon Musk',
            'zorluk': '2008 yılında hem Tesla hem SpaceX neredeyse iflas ediyordu. Kişisel tüm servetini bu iki şirkete yatırdı. 3. SpaceX fırlatması başarısız olsaydı şirket batacaktı.',
            'bugunku_durum': 'Şu anda Tesla, SpaceX ve daha birçok yenilikçi projenin başında. Dünyanın en zengin insanlarından biri.'
        },
        {
            'isim': 'Whitney Wolfe Herd',
            'zorluk': 'Tinder\'dan ayrıldıktan sonra cinsiyetçi mobbing ve iftira kampanyalarına maruz kaldı. Kendi girişimini kurarken yatırım almakta zorlandı. Kadın olduğu için ciddiye alınmadı.',
            'bugunku_durum': 'Bumble\'ı kurarak dünyanın en değerli kadın girişimcilerinden biri oldu. Genç yaşta milyarder oldu.'
        }
    ]
    
    for story in stories:
        YatirimciHikaye.objects.create(**story)

def remove_stories(apps, schema_editor):
    YatirimciHikaye = apps.get_model('core', 'YatirimciHikaye')
    YatirimciHikaye.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_yatirimcihikaye'),
    ]

    operations = [
        migrations.RunPython(load_stories, remove_stories),
    ]
