# Generated by Django 5.2.3 on 2025-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_load_investor_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('short_answer', models.CharField(max_length=255)),
                ('long_answer', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'SSS Sorusu',
                'verbose_name_plural': 'SSS Soruları',
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=255)),
                ('tooltip_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Yatırım Terimi',
                'verbose_name_plural': 'Yatırım Terimleri',
            },
        ),
    ]
